import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { DrawerProvider } from "./context";
import { Providers } from "./components/Provider";

const raleway = Raleway({
  weight: ["100", "200", "400", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
