import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { Flip, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./components/Provider";
import "./globals.css";
const raleway = Raleway({
  weight: ["100", "200", "400", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Providers>{children}</Providers>
        <ToastContainer
          position="bottom-left"
          newestOnTop={false}
          icon={false}
          hideProgressBar
          transition={Flip}
        />
      </body>
    </html>
  );
}
